# Documentation: http://docs.travis-ci.com/user/languages/julia/
dist: trusty
sudo: false
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
  - 0.6
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # Try using the master version of PyCall
  - julia -e 'ENV["PYTHON"] = ""; Pkg.clone("https://github.com/JuliaPy/PyCall.jl"); Pkg.build("PyCall")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Keras"); Pkg.test("Keras"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Keras")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'
